question_data = [
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The name of the main character of the video game 'The Legend of Zelda', is Zelda.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The main character in the 'Half-Life' franchise is named Morgan Freeman.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The movie 'The Nightmare before Christmas' was all done with physical objects.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Manchester United won the 2013-14 English Premier League.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The S in Harry S. Truman stands for 'Samuel'.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Linus Torvalds created Linux and Git.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "'Undertale' is an RPG created by Toby Fox and released in 2015.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There was a satirical candidate named 'Deez Nuts' running in the 2016 US presidential elections.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The 2010 film 'The Social Network' is a biographical drama film about MySpace founder Tom Anderson.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The programming language 'Python' is based off a modified version of 'JavaScript'.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Donkey Kong was originally set to be a Popeye arcade game.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The United States was a member of the League of Nations.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "RAM stands for Random Access Memory.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Sun rises from the North.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The color orange is named after the fruit.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "You can legally drink alcohol while driving in Mississippi.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Board Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The card game 'Munchkin' won the 2001 Origins Award for Best Traditional Card Game.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Alfred Hitchcock's film 'Psycho' it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There are no deserts in Europe.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Board Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Angry Video Game Nerd's alter ego is 'Board James'.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the 'Half-Life' series, 'H.E.V' stands for 'Hazardous Evasiveness Vest'",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The alternative rock band, They Might Be Giants, released their album 'Flood' in 1990. ",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the 'Toaru Kagaku no Railgun' anime,  espers can only reach a maximum of level 6 in their abilities.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Gadgets",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "One of Donald Trump's 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Time on Computers is measured via the EPOX System.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Windows ME operating system was released in the year 2000.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "'Minions' was released on the June 10th, 2015.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "'Metal Gear Solid 3: Snake Eater' was released in 2004.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the 'To Love-Ru' series, Golden Darkness is sent to kill Lala Deviluke.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Several characters in 'Super Mario 64' blink their eyes, including Mario himself.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "New Haven is the capital city of the state of Connecticut in the United States.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Psychology is the science of behavior and mind.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Nova Scotia is on the east coast of Canada.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Mythology",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A wyvern is the same as a dragon.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In 'Need for Speed: Porsche Unleashed', the player can only drive cars manufactured by Porsche.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Rhode Island is actually located on the US mainland, despite its name.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Vietnam's national flag is a red star in front of a yellow background.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Slovakia is a member of European Union-",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Rabbits are carnivores.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There are 2 player roles in Trouble in Terrorist Town.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The game 'Jetpack Joyride' was created by 'Redbrick Studios'.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
